project_id = "qnjpurehimuqppyrfxui"

[functions.send-invoice]
verify_jwt = false

[functions.send-receipt]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = false

[functions.create-signal]
verify_jwt = false