// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    // Exponential backoff on reconnect (1s, 2s, 4s, 8s … capped at 30s). A
    // realtime socket that can't authenticate otherwise retries in a tight
    // loop; that burst of auth traffic can trip Supabase's rate limit (HTTP
    // 429) on token refresh, which drops the session and bounces the admin
    // back to /admin/login a second after signing in. Backing off keeps a
    // failing socket from ever spiralling into a rate-limit lockout.
    reconnectAfterMs: (tries: number) => Math.min(1000 * 2 ** tries, 30000),
    heartbeatIntervalMs: 30000,
  },
});